apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
    #component: users
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8089
    #nodePort: 30001
  type: NodePort
